POST http://localhost:8080/candidate/
Content-Type: application/json

{
  "name": "simon",
  "username": "darksimon",
  "email": "simon@gmail.com",
  "password": "123456789",
  "description": "Primeiro usuario gestão de vagas"
}

